#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#

variables:
  GIT_DEPTH: 1
  GIT_STRATEGY: fetch

pages:
  artifacts:
    paths:
      - public
  script:
    - |
      for x in robots.txt sitemap.xml; do
        sed '
          s|manuals\.quinngrier\.com|quinngrier.gitlab.io/manuals|
        ' $x >$x.tmp || exit $?
        mv $x.tmp $x || exit $?
      done
      xs=`git ls-tree --name-only HEAD:` || exit $?
      rm -f -r public || exit $?
      mkdir public || exit $?
      cp -L -R -- $xs public || exit $?

sourceforge:
  script:
    - |
      for x in robots.txt sitemap.xml; do
        sed '
          s|manuals\.quinngrier\.com|manuals.sourceforge.io|
        ' $x >$x.tmp || exit $?
        mv $x.tmp $x || exit $?
      done
      chmod 600 -- "${SOURCEFORGE_SSH_SECRET_KEY?}" || exit $?
      xs=`git ls-tree --name-only HEAD:` || exit $?
      scp \
        -i "${SOURCEFORGE_SSH_SECRET_KEY?}" \
        -o IdentitiesOnly=yes \
        -o PasswordAuthentication=no \
        -o PreferredAuthentications=publickey \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -r \
        -- \
        $xs \
        quinngrier@web.sourceforge.net:/home/project-web/manuals/htdocs \
      || exit $?
