#! /bin/sh -
#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#

set -e || exit $?
. ./prelude.bash

make -s do_timestamps

rm -f -r footmp1

git clone -q . footmp1
cd footmp1
git log --date=unix --format=@%cd --name-only | awk '
  {
    if (/^@/) {
      lastmod = substr($0, 2);
    } else if (/^./ && !seen[$0]) {
      print $0, lastmod;
      seen[$0] = 1;
    }
  }
' | ../do_timestamps
rm -f -r .git

xs=$(find . -type l)
for x in $xs; do
  cp -L -R -p "$x" flatten.tmp
  rm -f -r "$x"
  mv flatten.tmp "$x"
done

aws s3 sync \
  . \
  s3://manuals.quinngrier.com \
  --delete \
  --exact-timestamps \
  --profile quinn \
  --storage-class INTELLIGENT_TIERING \
;

cd ..

rm -f -r footmp1
