#! /bin/sh -

#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#

set -e || exit $?
. ./prelude.bash

./index

if [[ ${PWD##*/} != manuals ]]; then
  qsh_barf "Current directory must be named \"manuals\""
fi

x=$(git status --ignored -s)
if [[ "$x" ]]; then
  qsh_barf "Repository is not clean"
fi

if [[ -e ../manuals.git ]]; then
  qsh_barf "../manuals.git already exists"
fi

if [[ -e ../manuals.tar.zst ]]; then
  qsh_barf "../manuals.tar.zst already exists"
fi

make -s set_timestamps

git log --date=unix --format=@%cd --name-only | awk '
  {
    if (/^@/) {
      lastmod = substr($0, 2);
    } else if (/^./ && !seen[$0]) {
      print $0, lastmod;
      seen[$0] = 1;
    }
  }
' | ./set_timestamps

rm set_timestamps

xs=$(find . -name .git -prune -o -type l -print)
for x in $xs; do
  cp -L -R -p "$x" flatten.tmp
  rm -f -r "$x"
  mv flatten.tmp "$x"
done

t=$(git log -1 --format=@%ct)
readonly t

mv .git ../manuals.git

( : \
  && cd .. \
  && find manuals -type d -exec touch -d $t {} + \
  && tar -c \
       --group=0 \
       --mode=u=rwX,go=rX \
       --numeric-owner \
       --owner=0 \
       --sort=name \
       manuals \
     | zstd -19 -T0 >manuals.tar.zst \
  && touch -d $t manuals.tar.zst \
  && mv manuals.tar.zst manuals \
  && touch -d $t manuals \
  && cd manuals \
  && aws s3 sync \
       . \
       s3://manuals \
       --delete \
       --exact-timestamps \
       --profile quinn_r2 \
) && :
x=$?

mv ../manuals.git .git

rm -f manuals.tar.zst ../manuals.tar.zst

git reset --hard -q

exit $x
