#! /bin/sh -

#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#

set -e || exit $?
. ./prelude.bash

x=$(git status --ignored -s)
if [[ "$x" ]]; then
  qsh_barf "Repository is not clean"
fi

if [[ -e ../manuals.git ]]; then
  printf '%s\n' "../manuals.git already exists." >&2
  exit 1
fi

make -s set_timestamps

git log --date=unix --format=@%cd --name-only | awk '
  {
    if (/^@/) {
      lastmod = substr($0, 2);
    } else if (/^./ && !seen[$0]) {
      print $0, lastmod;
      seen[$0] = 1;
    }
  }
' | ./set_timestamps

rm set_timestamps

skip_git='( ! -name .git -o -prune )'

xs=$(find . $skip_git -type l)
for x in $xs; do
  cp -L -R -p "$x" flatten.tmp
  rm -f -r "$x"
  mv flatten.tmp "$x"
done

mv .git ../manuals.git

aws s3 sync \
  . \
  s3://manuals \
  --delete \
  --exact-timestamps \
  --profile quinn_r2 \
&& :
x=$?

mv ../manuals.git .git

git reset --hard -q

exit $x
