#! /bin/sh -
#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#

set -e || exit $?
. ${1-./}prelude.bash

main() {

  declare    current
  declare    d
  declare    h
  declare    ignore
  declare    lastmod
  declare    root
  declare    sitemap_end
  declare    sitemap_start
  declare    skip
  declare    x
  declare    xs

  root=${1-./}
  readonly root

  current=${2-./}
  readonly current

  >index.html

  cat <<EOF >>index.html
<!DOCTYPE html>
<!--
The authors of this file have waived all copyright and
related or neighboring rights to the extent permitted by
law as described by the CC0 1.0 Universal Public Domain
Dedication. You should have received a copy of the full
dedication along with this file, typically as a file
named <CC0-1.0.txt>. If not, it may be available at
<https://creativecommons.org/publicdomain/zero/1.0/>.
-->
<html>
<head>
<meta charset="UTF-8">
<title>/${current#./} - Quinn's Manuals Archive</title>
<style>

:root {
  --line_height: 1.2em;
  --text_color: #CCC;
  --tree_border: 1px solid #333;
}

body {
  background: #000;
  color: var(--text_color);
  font-family: monospace;
  font-size: 20px;
  line-height: var(--line_height);
  margin: 1em;
}

a {
  color: var(--text_color);
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

ul {
  list-style-type: none;
  margin: 0 0 0 0.5ch;
  padding: 0;
  position: relative;
}

li:first-child {
  border-left: var(--tree_border);
  display: block;
  height: calc(100% - var(--line_height) / 2);
  left: 0;
  position: absolute;
  right: 100%;
  top: 0;
}

li:not(:first-child) {
  margin-left: 0.25ch;
}

li:not(:first-child)::before {
  border-top: var(--tree_border);
  content: "";
  display: inline-block;
  left: -0.25ch;
  position: relative;
  transform: translateY(calc(var(--line_height) / 2));
  vertical-align: top;
  width: 1.25ch;
}

</style>
</head>
<body>
EOF

  h=
  d=./
  x=$current
  while [[ $x != ./ ]]; do
    x=${x%/}
    h="<a href=\"$d\">${x##*/}/</a>$h"
    d+=../
    d=${d#./}
    x=${x%/*}/
  done
  h="<a href=\"$d\">/</a>$h"

  cat <<EOF >>index.html
$h
<ul>
<li></li>
EOF

  if [[ -f ignore ]]; then
    ignore=' '$(
      sed $'/^[\t ]*#/ d' <ignore | tr '\t\n\v\f\r' '[ *]'
    )' '
  else
    ignore=
  fi
  readonly ignore

  xs=$(
    for x in */; do
      if [[ $x == .* || "$ignore" == *" $x "* ]]; then
        continue
      fi
      x=${x%/}
      if [[ -f $x/date ]]; then
        d=$(cat $x/date)
      else
        d=0000-00-00
      fi
      printf '%s\n' "$d $x"
    done | sort | cut -d ' ' -f 2
  )

  for x in $xs; do
    cat <<EOF >>index.html
<li><a href="$x/">$x/</a></li>
EOF
  done

  if [[ -f files ]]; then
    xs=$(cat files)
    for x in $xs; do
      cat <<EOF >>index.html
<li><a href="$x">$x</a></li>
EOF
    done
  fi

  cat <<'EOF' >>index.html
</ul>
</body>
</html>
EOF

  if [[ -f skip ]]; then
    skip=' '$(
      sed $'/^[\t ]*#/ d' <skip | tr '\t\n\v\f\r' '[ *]'
    )' '
  else
    skip=
  fi
  readonly skip

  for d in */; do
    if [[ $d == .* || "$ignore $skip" == *" $d "* ]]; then
      continue
    fi
    cd $d
    ../$0 ../$root $current$d
    cd ..
  done

  #---------------------------------------------------------------------
  # Generate the sitemap
  #---------------------------------------------------------------------

  if [[ $current == ./ ]]; then

    sitemap_start='<?xml version="1.0" encoding="UTF-8"?>

<!--
The authors of this file have waived all copyright and
related or neighboring rights to the extent permitted by
law as described by the CC0 1.0 Universal Public Domain
Dedication. You should have received a copy of the full
dedication along with this file, typically as a file
named <CC0-1.0.txt>. If not, it may be available at
<https://creativecommons.org/publicdomain/zero/1.0/>.
-->

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
'
    readonly sitemap_start

    sitemap_end='
</urlset>
'
    readonly sitemap_end

    make -s do_timestamps

    rm -f -r footmp1 footmp2

    (
      git clone -q . footmp1
      cd footmp1
      git log --date=unix --format=@%cd --name-only | awk '
        {
          if (/^@/) {
            lastmod = substr($0, 2);
          } else if (/^./ && !seen[$0]) {
            print $0, lastmod;
            seen[$0] = 1;
          }
        }
      ' | ../do_timestamps
      rm -f -r .git
    )

    (
      cp -L -R -p footmp1 footmp2
      cd footmp2
      TZ=UTC find . -type f -printf '%p %TY-%Tm-%TdT%TH:%TM:%TS\n'
    ) | (sort; echo @EOF) | (

      declare    file
      declare    i
      declare    lastmod
      declare    max_bytes
      declare    max_entries
      declare    max_lastmod
      declare    n_bytes
      declare    n_entries
      declare    urlstr

      max_bytes=49000000
      readonly max_bytes

      max_entries=49000
      readonly max_entries

      exec 3>sitemap.xml

      printf %s '<?xml version="1.0" encoding="UTF-8"?>

<!--
The authors of this file have waived all copyright and
related or neighboring rights to the extent permitted by
law as described by the CC0 1.0 Universal Public Domain
Dedication. You should have received a copy of the full
dedication along with this file, typically as a file
named <CC0-1.0.txt>. If not, it may be available at
<https://creativecommons.org/publicdomain/zero/1.0/>.
-->

<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
' >&3

      i=0
      n_bytes=$((max_bytes + 1))
      n_entries=0
      max_lastmod=

      while IFS= read -r file; do
        lastmod=${file##* }
        file=${file% *}
        if [[ "$file" == @EOF ]]; then
          break
        fi
        if [[ "$file" == ./sitemap* ]]; then
          continue
        fi
        file=${file:2}
        lastmod=${lastmod%.*}+00:00
        if ((n_bytes > max_bytes || n_entries > max_entries)); then
          if ((i > 0)); then
            printf %s "$sitemap_end" >&4
            exec 4>&-
            printf %s "
  <sitemap>
    <loc>https://manuals.quinngrier.com/sitemap-$i.xml</loc>
    <lastmod>$max_lastmod</lastmod>
  </sitemap>
" >&3
          fi
          ((++i))
          n_bytes=$((${#sitemap_start} + ${#sitemap_end}))
          n_entries=0
          max_lastmod=
          exec 4>sitemap-$i.xml
          printf %s "$sitemap_start" >&4
        fi
        if [[ $lastmod > $max_lastmod ]]; then
          max_lastmod=$lastmod
        fi
        urlstr="
  <url>
    <loc>https://manuals.quinngrier.com/$file</loc>
    <lastmod>$lastmod</lastmod>
  </url>
"
        ((n_bytes += ${#urlstr}))
        ((++n_entries))
        printf %s "$urlstr" >&4
      done
      if [[ "$file" != @EOF ]]; then
        exit 1
      fi

      if ((i > 0)); then
        printf %s "$sitemap_end" >&4
        exec 4>&-
        printf %s "
  <sitemap>
    <loc>https://manuals.quinngrier.com/sitemap-$i.xml</loc>
    <lastmod>$max_lastmod</lastmod>
  </sitemap>
" >&3
      fi

      printf %s '
</sitemapindex>
' >&3

      exec 3>&-

    )

    rm -f -r footmp1 footmp2

  fi

  #---------------------------------------------------------------------

}; readonly -f main

main "$@"
