//
// The authors of this file have waived all copyright and
// related or neighboring rights to the extent permitted by
// law as described by the CC0 1.0 Universal Public Domain
// Dedication. You should have received a copy of the full
// dedication along with this file, typically as a file
// named <CC0-1.0.txt>. If not, it may be available at
// <https://creativecommons.org/publicdomain/zero/1.0/>.
//

= Quinn's Manuals Archive

:quinngrier: quinngrier
:subs_source: specialchars,attributes,quotes,macros

link:https://manuals.{quinngrier}.com/[Quinn's Manuals Archive]
is a static site that archives manuals for long-term reference purposes.

Selection permalinking has been added to the manuals wherever possible
using link:https://github.com/quinngrier/qref[Qref].
The manuals are eventually stable with respect to Qref links, with
breaking changes made only to fix significant rendering problems.

== Mirroring

Download the
link:https://manuals.{quinngrier}.com/manuals.tar.zst[tarball]
of the site, extract it, and host it however you like.

Some files hardcode `+https://manuals.{quinngrier}.com/+`.
Here's how to change this to your own URL:

[source,subs="{subs_source}"]
----
old_url='https://manuals.{quinngrier}.com/'
new_url='https://example.com/'
grep -F -I -Z -l -r "$old_url" manuals | xargs -0 sh -c '
  set -e -u || exit
  old_url=$(sed '\''s/./[&]/g'\'' <<EOF
$1
EOF
  )
  new_url=$(sed '\''s/&/\\&/g'\'' <<EOF
$2
EOF
  )
  shift 2
  for x; do
    sed "s|$old_url|$new_url|g" "$x" >tmp
    touch -r "$x" tmp
    cat tmp >"$x"
    touch -r tmp "$x"
  done
  rm -f tmp
' sh "$old_url" "$new_url"
----

Optionally, you can also add `sitemap.xml` to your `robots.txt`.

Optionally, you can also host the tarball.

//
