#! /bin/sh -
#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#

set -e || exit $?
. ../../prelude.bash

main() {

  declare    container
  declare    image
  declare    url
  declare    v
  declare    v1
  declare    v2
  declare    x

  v=${PWD##*/}
  readonly v

  v1=${v%%.*}
  readonly v1

  v2=${v#"$v1."}
  v2=${v2%%[-.]*}
  readonly v2

  rm -f automake-$v.tar.gz
  ln -s ../../downloads/automake-$v.tar.gz automake-$v.tar.gz
  if [[ ! -f automake-$v.tar.gz ]]; then
    url=https://ftp.gnu.org/gnu/automake/automake-$v.tar.gz
    wget -O - -- "$url" >automake-$v.tar.gz
  fi
  sha512sum -c --quiet automake-$v.tar.gz.sha512sum
  cp -L automake-$v.tar.gz automake-$v.tar.gz.flat

  rm -f texinfo-6.7.tar.gz
  ln -s ../../downloads/texinfo-6.7.tar.gz texinfo-6.7.tar.gz
  if [[ ! -f texinfo-6.7.tar.gz ]]; then
    url=https://ftp.gnu.org/gnu/texinfo/texinfo-6.7.tar.gz
    wget -O - -- "$url" >texinfo-6.7.tar.gz
  fi
  sha512sum -c --quiet texinfo-6.7.tar.gz.sha512sum
  cp -L texinfo-6.7.tar.gz texinfo-6.7.tar.gz.flat

  rm -f -r automake-$v
  tar xzf automake-$v.tar.gz
  x=$(find automake-$v -type f -printf '%T@\n' | sort -n | tail -1)
  {
    printf %02d%02d: "$v1" "$v2"
    date -d "@$x" -u +%Y-%m-%d
  } >date

  cp -L Dockerfile Dockerfile.flat
  cp -L build-html.bash build-html.bash.flat
  docker build -f Dockerfile.flat --iidfile image .

  image=$(cat image)
  readonly image

  container=$(docker create $image)
  readonly container

  rm -f -r out
  mkdir out

  docker cp $container:/automake/automake/out/. out

  docker rm $container

  >files
  for x in out/*; do
    sed '
      s|</head>|<script defer src="qref.js"></script>&|
    ' $x >$x.tmp
    mv -f $x.tmp $x
    echo ${x#out/} >>files
  done

  mv -f out/* .

  rm -f -r \
    Dockerfile.flat \
    automake-$v \
    automake-$v.tar.gz \
    automake-$v.tar.gz.flat \
    build-html.bash.flat \
    image \
    out \
    texinfo-6.7.tar.gz \
    texinfo-6.7.tar.gz.flat \
  ;

}; readonly -f main

main "$@"
