#! /bin/sh -
#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#

set -e || exit $?
. ../../prelude.bash

main() {

  declare    container
  declare    image
  declare    url
  declare    x

  url=https://ftp.gnu.org/gnu/bash/bash-4.0.tar.gz
  rm -f -r bash-4.0.tar.gz bash-4.0
  wget -O bash-4.0.tar.gz -- "$url"
  sha512sum -c bash-4.0.tar.gz.sha512sum

  url=http://ftp.gnu.org/gnu/groff/groff-1.22.4.tar.gz
  rm -f -r groff-1.22.4.tar.gz groff-1.22.4
  wget -O groff-1.22.4.tar.gz -- "$url"
  sha512sum -c groff-1.22.4.tar.gz.sha512sum

  url=http://ftp.gnu.org/gnu/texinfo/texinfo-6.7.tar.gz
  rm -f -r texinfo-6.7.tar.gz texinfo-6.7
  wget -O texinfo-6.7.tar.gz -- "$url"
  sha512sum -c texinfo-6.7.tar.gz.sha512sum

  docker build --iidfile image .

  image=$(cat image)
  readonly image

  container=$(docker create $image)
  readonly container

  rm -f -r out
  mkdir out

  docker cp $container:/bash-4.0/doc/out/. out

  docker rm $container

  for x in out/*; do
    sed '
      s|</head>|<script defer src="qref.js"></script>&|
    ' $x >$x.tmp
    mv -f $x.tmp $x
  done

  mv -f out/* .

  rm bash-4.0.tar.gz
  rm groff-1.22.4.tar.gz
  rm image
  rm texinfo-6.7.tar.gz
  rmdir out

}; readonly -f main

main "$@"
