#! /bin/sh -
#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#

set -e || exit $?
. ../../prelude.bash

clean() {
  rm -f -r \
    repo \
    tmp \
  ;
}; readonly -f clean

main() {

  local    g
  local    u
  local    url
  local    x
  local    y

  url=https://github.com/twbs/bootstrap.git
  rm -f -r repo
  git clone --branch v3.4.1 --depth 1 "$url" repo
  rm -f -r repo/.git
  sha256sum --check --quiet repo.sha256sum
  sha512sum --check --quiet repo.sha512sum

  cd repo

  sed '
    s|^url:.*|url: https://manuals.quinngrier.com|
    s|^baseurl:.*|baseurl: /bootstrap/3.4.1/gh-pages|
  ' _config.yml >tmp
  mv -f tmp _config.yml

  for x in docs/_includes/**/*.html; do
    sed '
      /<link.*https:/ d
      /<script.*https:/ d
      /GoogleAnalyticsObject/,/pageview/ d
    ' $x >tmp
    mv -f tmp $x
  done

  u=$(id -u)
  readonly u

  g=$(id -g)
  readonly g

  docker run \
    --rm \
    -i \
    -t \
    -v "$PWD":/srv/jekyll \
    jekyll/jekyll:4.2.0 \
    sh -c ': \
      && gem install bundler:1.17.3 \
      && bundle install \
      && bundle exec jekyll build \
      && chown -R '$u:$g' . \
    ' \
  ;

  rm -f -r ../gh-pages
  mv -f _gh_pages ../gh-pages

  cd ..

  rm -f gh-pages/sitemap.xml

  for x in gh-pages/**/*.html; do
    y=$(sed 's|[^/]*/|../|g' <<<${x%/*}/)qref.js
    sed '
      s|</head>|<script defer src="'$y'"></script>&|
    ' $x >$x.tmp
    mv -f $x.tmp $x
  done

  rm -f -r repo

}; readonly -f main

main "$@"
