#! /bin/sh -
#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#

set -e || exit $?
. ../../../prelude.bash

main() {

  rm -f -r repo
  git clone \
    --depth 1 \
    -b 3.1.2 \
    https://github.com/mathjax/MathJax.git \
    repo \
  ;
  cd repo
  git checkout c8292351190ce249f7143f224dbe7a190c8228fe
  cd es5
  for x in ./*; do
    rm -f -r "../../${x##*/}"
    mv -f "$x" ../..
  done
  cd ../..
  rm -f -r repo

}; readonly -f main

main "$@"
