#! /bin/sh -
#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#

set -e || exit $?
. ../../prelude.bash

main() {

  declare    container
  declare    image
  declare    v
  declare    v1
  declare    v2
  declare    x

  v=${PWD##*/}
  readonly v

  v1=${v%%.*}
  readonly v1

  v2=${v#"$v1."}
  v2=${v2%%[.-]*}
  readonly v2

  download gm4/m4-$v.tar.gz
  download groff/groff-1.22.4.tar.gz
  download texinfo/texinfo-6.7.tar.gz

  rm -f -r m4-$v
  tar xzf m4-$v.tar.gz
  x=$(find m4-$v -type f -printf '%T@\n' | sort -n | tail -1)
  {
    printf %03d%03d: "$v1" "$v2"
    date -d "@$x" -u +%Y-%m-%d
  } >date

  cp ../common/* .
  cp "$prelude_dir"/prelude.bash .

  docker build --iidfile image .
  image=$(cat image)
  readonly image

  container=$(docker create $image)
  readonly container

  rm -f -r out
  mkdir out

  docker cp $container:/m4/m4/out/. out

  docker rm $container

  >files
  for x in out/*; do
    sed '
      s|</head>|<script defer src="qref.js"></script>&|
    ' $x >$x.tmp
    mv -f $x.tmp $x
    echo ${x#out/} >>files
  done

  mv -f out/* .

  rm -f -r \
    Dockerfile \
    build-html.bash \
    groff-*.tar.gz \
    image \
    m4-$v \
    m4-$v.tar.gz \
    out \
    prelude.bash \
    texinfo-*.tar.gz \
  ;

}; readonly -f main

main "$@"
